# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PetUi
                                 A QGIS plugin
 Physiological Equivalent Temperature Simulator
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-08-02
        copyright            : (C) 2023 by Marieke van Esch, student TU Delft, the Netherlands
        email                : marieke.vanesch@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PetUi class from file PetUi.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .pet_simulator import PetUi
    return PetUi(iface)
